<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'If you check this, the kid\'s name won\'t show in lists, but nothing will be deleted.' => 'Ha inaktívvá teszed, nem fog látszódni a listákban, de nem fognak törlődni az adatai.',
    'Address' => 'Lakcím',
    'Advanced search' => 'Részletes keresés',
    'Age (from)' => 'Kor (tól)',
    'Age (to)' => 'Kor (ig)',
    'All group' => 'Minden csoport',
    'Are you sure? Every data belongs this kid will be deleted!' => 'Biztos vagy benne? Minden adat, ami a gyerekhez kapcsolódik törlődni fog!',
    'Base data' => 'Alapadatok',
    'Birth date' => 'Születési dátum',
    'Class nr. / Group name' => 'Osztály száma / Csoport neve',
    'Contact' => 'Kapcsolat',
    'Create successful' => 'Sikeres létrehozás',
    'Create unsuccessful' => 'Sikertelen létrehozás',
    'Created at' => 'Létrehozva',
    'Created by' => 'Létrehozta',
    'Delete' => 'Törlés',
    'Documents' => 'Dokumentumok',
    'Educator name' => 'Pedagógus neve',
    'Educator office hours' => 'Pedagógus fogadóórái',
    'Educator phone' => 'Pedagógus telefonszáma',
    'Error' => 'Hiba',
    'Family name' => 'Család',
    'GPS lat' => 'GPS szélesség',
    'GPS lon' => 'GPS hosszúság',
    'Gallery' => 'Galéria',
    'Group' => 'Csoport',
    'Groups' => 'Csoportok',
    'Inactive' => 'Inaktív',
    'Kid model class not found!' => 'A gyerekek modelje nem található',
    'Kid phone number' => 'Gyerek telefonszáma',
    'Kids' => 'Gyerekek',
    'Name' => 'Név',
    'New kid' => 'Új gyerek',
    'Notes' => 'Jegyzetek',
    'Other' => 'Egyéb',
    'Parent contact' => 'Szülők elérhetőségei',
    'Profile image' => 'Profilkép',
    'Responsibles' => 'Felelősök',
    'Save' => 'Mentés',
    'School / Kindergarten' => 'Iskola / Óvoda',
    'School / Kindergarten name' => 'Iskola / Óvoda neve',
    'Search' => 'Keresés',
    'Search by name, family name, or other data' => 'Keress név, családnév, vagy egyéb adatok alapján',
    'Update' => 'Módosít',
    'Update kid: {name}' => 'Gyerek adatainak módosítása: {name}',
    'Update successful' => 'Sikeres módosítás',
    'Update unsuccessful' => 'Sikertelen módosítás',
    'Updated at' => 'Utoljára módosítva',
    'Updated by' => 'Utoljára módosította',
    '{age} years old' => '{age} éves',
];
